kind: Deployment
apiVersion: apps/v1
metadata:
  name: bootcamp-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bootcamp-client
  template:
    metadata:
      labels:
        app: bootcamp-client
    spec:
      containers:
        - name: bootcamp
          image: tchung0421/bootcamp-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
